/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Cpu.c
**     Project     : exp-the-motor
**     Processor   : MC56F8257
**     Component   : 56F8257
**     Version     : Component 01.014, Driver 02.10, CPU db: 3.00.239
**     Datasheet   : MC56F824x/5xPB Rev. 1.0.0, 09/2008; MC56F82XXRM Rev. 0 Draft A 11/2008
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2021-05-31, 16:21, # CodeGen: 57
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         EnableInt   - void Cpu_EnableInt(void);
**         DisableInt  - void Cpu_DisableInt(void);
**         SetWaitMode - void Cpu_SetWaitMode(void);
**         SetStopMode - void Cpu_SetStopMode(void);
**
**     (c) Freescale Semiconductor, Inc.
**     2004 All Rights Reserved
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.c
** @version 02.10
** @brief
**
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

/* MODULE Cpu. */
#include "Bit1.h"
#include "Bit2.h"
#include "TI1.h"
#include "eFlexPWM.h"
#include "Cap1.h"
#include "Cap2.h"
#include "PWMC1.h"
#include "Cap3.h"
#include "FMSTR1.h"
#include "QSCI0.h"
#include "TI2.h"
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Events.h"
#include "Cpu.h"

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */


/* Global variables */
volatile word SR_lock = 0U;            /* Lock */
volatile word SR_reg;                  /* Current value of the SR register */
/*
** ===================================================================
**     Method      :  Cpu_Interrupt (component 56F8257)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma interrupt alignsp
void Cpu_Interrupt(void)
{
  asm(DEBUGHLT);                       /* Halt the core and placing it in the debug processing state */
}

/*
** ===================================================================
**     Method      :  Cpu__ivINT_TMRA1 (component 56F8257)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma interrupt alignsp saveall
void Cpu__ivINT_TMRA1(void)
{
  word regFlag_TMRA1_SCTRL = getReg(TMRA1_SCTRL);
  word regFlag_TMRA1_CSCTRL = getReg(TMRA1_CSCTRL);

  if ((regFlag_TMRA1_CSCTRL & TMRA1_CSCTRL_TCF1EN_MASK) && (regFlag_TMRA1_CSCTRL & TMRA1_CSCTRL_TCF1_MASK)) { /* Is the device enabled and an interrupt flag is set? */
    clrRegBit(TMRA1_CSCTRL, TCF1);     /* If yes then clear an interrupt flag */
  }
  if (regFlag_TMRA1_SCTRL & TMRA1_SCTRL_IEFIE_MASK) { /* Is the device enabled? */
    if (regFlag_TMRA1_SCTRL & TMRA1_SCTRL_IEF_MASK) { /* Is the interrupt flag set? */
      Cap2_Interrupt();                /* Call the service routine */
    }
  }
  if (regFlag_TMRA1_CSCTRL & TMRA1_CSCTRL_TCF1EN_MASK) { /* Is the device enabled? */
    if (regFlag_TMRA1_CSCTRL & TMRA1_CSCTRL_TCF1_MASK) { /* Is the interrupt flag set? */
      TI2_Interrupt();                 /* Call the service routine */
    }
  }
}

/*
** ===================================================================
**     Method      :  Cpu__ivINT_TMRA0 (component 56F8257)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma interrupt alignsp saveall
void Cpu__ivINT_TMRA0(void)
{
  word regFlag_TMRA0_CSCTRL = getReg(TMRA0_CSCTRL);
  word regFlag_TMRA0_SCTRL = getReg(TMRA0_SCTRL);

  if ((regFlag_TMRA0_CSCTRL & TMRA0_CSCTRL_TCF1EN_MASK) && (regFlag_TMRA0_CSCTRL & TMRA0_CSCTRL_TCF1_MASK)) { /* Is the device enabled and an interrupt flag is set? */
    clrRegBit(TMRA0_CSCTRL, TCF1);     /* If yes then clear an interrupt flag */
  }
  if (regFlag_TMRA0_CSCTRL & TMRA0_CSCTRL_TCF1EN_MASK) { /* Is the device enabled? */
    if (regFlag_TMRA0_CSCTRL & TMRA0_CSCTRL_TCF1_MASK) { /* Is the interrupt flag set? */
      TI1_Interrupt();                 /* Call the service routine */
    }
  }
  if (regFlag_TMRA0_SCTRL & TMRA0_SCTRL_IEFIE_MASK) { /* Is the device enabled? */
    if (regFlag_TMRA0_SCTRL & TMRA0_SCTRL_IEF_MASK) { /* Is the interrupt flag set? */
      Cap1_Interrupt();                /* Call the service routine */
    }
  }
}

/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component 56F8257)
**     Description :
**         Disables all maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component 56F8257)
**     Description :
**         Enables all maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetStopMode (component 56F8257)
**     Description :
**         Sets low power mode - Stop mode.
**         For more information about the stop mode see this CPU
**         documentation.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetStopMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetWaitMode (component 56F8257)
**     Description :
**         Sets low power mode - Wait mode.
**         For more information about the wait mode see this CPU
**         documentation.
**         Release from wait mode: Reset or interrupt
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetWaitMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  _EntryPoint (component 56F8257)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
extern void init_56800_(void);         /* Forward declaration of external startup function declared in startup file */

/*** !!! Here you can place your own code using property "User data declarations" on the build options tab. !!! ***/

void _EntryPoint(void)
{
  #pragma constarray off

  /*** !!! Here you can place your own code before PE initialization using property "User code before PE initialization" on the build options tab. !!! ***/

  /*** ### MC56F8257 "Cpu" init code ... ***/
  /*** PE initialization code after reset ***/
  /* System clock initialization */
  setRegBitGroup(OCCS_OSCTL, TRIM, (word)getReg(FM_OPT0) & 0x03FFU); /* Set the trim osc freq with factory programmed value */
  setRegBit(OCCS_OSCTL, CLK_MODE);     /* Select an internal oscillator mode */
  clrRegBit(OCCS_CTRL, PRECS);         /* Select an internal clock source for the CPU core */
  setReg(OCCS_CTRL, (OCCS_CTRL_LCKON_MASK | OCCS_CTRL_ZSRC0_MASK)); /* Enable PLL, LCKON and select clock source from prescaler */
  /* OCCS_DIVBY: LORTP=2,COD=0,??=0,PLLDB=0x1D */
  setReg16(OCCS_DIVBY, 0x201DU);       /* Set the clock prescalers */ 
  while(!getRegBit(OCCS_STAT, LCK0)){} /* Wait for PLL lock */
  setReg(OCCS_CTRL, (OCCS_CTRL_LCKON_MASK | OCCS_CTRL_ZSRC1_MASK)); /* Select clock source from postscaler */
  /* FM_CLKDIV: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,DIVLD=0,PRDIV8=0,DIV=0x28 */
  setReg16(FM_CLKDIV, 0x28U);          /* Set the flash clock prescaler */ 
  /*** End of PE initialization code after reset ***/

  /*** !!! Here you can place your own code after PE initialization using property "User code after PE initialization" on the build options tab. !!! ***/

  setReg(COP_CTRL, 0);                 /* Disable COP running after reset */
  asm(JMP init_56800_);                /* Jump to C startup code */
}

/*
** ===================================================================
**     Method      :  PE_low_level_init (component 56F8257)
**
**     Description :
**         Initializes beans and provides common register initialization. 
**         The method is called automatically as a part of the 
**         application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  /* SIM_SD0: TA0=0,TA1=0,TA2=0,TA3=0,TB0=0,TB1=0,TB2=0,TB3=0,ADC=0,GPIOA=0,GPIOB=0,GPIOC=0,GPIOD=0,GPIOE=0,GPIOF=0,??=0 */
  setReg16(SIM_SD0, 0x00U);            /* Set up the STOP disable register 0 */ 
  /* SIM_SD1: ??=0,DAC=0,CMPA=0,CMPB=0,CMPC=0,SCI0=0,SCI1=0,QSPI0=0,IIC0=0,IIC1=0,CRC=0,REFA=0,REFB=0,REFC=0,??=0,MSCAN=0 */
  setReg16(SIM_SD1, 0x00U);            /* Set up the STOP disable register 1 */ 
  /* SIM_SD2: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,PWMCH0=0,PWMCH1=0,PWMCH2=0,PWMCH3=0 */
  setReg16(SIM_SD2, 0x00U);            /* Set up the STOP disable register 2 */ 
/* Enable peripheral clock */
  /* SIM_PCE0: TA0=1,TA1=1,TA2=1,GPIOB=1,GPIOC=1,GPIOE=1,GPIOF=1 */
  setReg16Bits(SIM_PCE0, 0xE036U);     /* Enable prph.clocks in the SIM_PCE0 register before Common initialization */ 
  /* SIM_PCE1: SCI0=1,HFM=1,MSCAN=1 */
  setReg16Bits(SIM_PCE1, 0x0403U);     /* Enable prph.clocks in the SIM_PCE1 register before Common initialization */ 
  /* SIM_PCE2: PWMCH0=1,PWMCH1=1,PWMCH2=1 */
  setReg16Bits(SIM_PCE2, 0x0EU);       /* Enable prph.clocks in the SIM_PCE2 register before Common initialization */ 
  /* GPIO_A_DRIVE: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  setReg16(GPIO_A_DRIVE, 0x00U);       /* Set High/Low drive strength on GPIOA pins according to the CPU bean settings */ 
  /* GPIO_B_DRIVE: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  setReg16(GPIO_B_DRIVE, 0x00U);       /* Set High/Low drive strength on GPIOB pins according to the CPU bean settings */ 
  /* GPIO_C_DRIVE: DRIVE15=0,DRIVE14=0,DRIVE13=0,DRIVE12=0,DRIVE11=0,DRIVE10=0,DRIVE9=0,DRIVE8=0,DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  setReg16(GPIO_C_DRIVE, 0x00U);       /* Set High/Low drive strength on GPIOC pins according to the CPU bean settings */ 
  /* GPIO_D_DRIVE: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  setReg16(GPIO_D_DRIVE, 0x00U);       /* Set High/Low drive strength on GPIOD pins according to the CPU bean settings */ 
  /* GPIO_E_DRIVE: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  setReg16(GPIO_E_DRIVE, 0x00U);       /* Set High/Low drive strength on GPIOE pins according to the CPU bean settings */ 
  /* GPIO_F_DRIVE: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,DRIVE8=0,DRIVE7=0,DRIVE6=0,DRIVE5=0,DRIVE4=0,DRIVE3=0,DRIVE2=0,DRIVE1=0,DRIVE0=0 */
  setReg16(GPIO_F_DRIVE, 0x00U);       /* Set High/Low drive strength on GPIOF pins according to the CPU bean settings */ 
  /* SIM_PCR: TMRA_CR=0,TMRB_CR=0,SCI0_CR=0,SCI1_CR=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(SIM_PCR, 0x00U);            /* Set the TMR; TMRB; QSCI0; QSCI1 module clock rates */ 
  /* SIM_CTRL: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,ONCEEBL=0,SWRST=0,STOP_DISABLE=0,WAIT_DISABLE=0 */
  setReg16(SIM_CTRL, 0x00U);           /* Set up the SIM control register */ 
  /* SIM_CLKOUT: ??=0,??=0,??=1,??=0,??=0,??=0,??=0,??=0,??=0,TEST=0,CLKDIS=1,CLKOSEL=0 */
  setReg16(SIM_CLKOUT, 0x2020U);       /* Set up the SIM clock output select register */ 
  /* Common initialization of the CPU registers */
  /* GPIO_B_IEN: IEN3=0,IEN2=0 */
  clrReg16Bits(GPIO_B_IEN, 0x0CU);      
  /* GPIO_B_IASSRT: IA3=0,IA2=0 */
  clrReg16Bits(GPIO_B_IASSRT, 0x0CU);   
  /* GPIO_B_IEDGE: IES3=1,IES2=1 */
  setReg16Bits(GPIO_B_IEDGE, 0x0CU);    
  /* GPIO_B_PPOUTM: PPMODE3=1,PPMODE2=1 */
  setReg16Bits(GPIO_B_PPOUTM, 0x0CU);   
  /* GPIO_B_DATA: D3=0,D2=0 */
  clrReg16Bits(GPIO_B_DATA, 0x0CU);     
  /* GPIO_B_DDIR: DD3=1,DD2=1 */
  setReg16Bits(GPIO_B_DDIR, 0x0CU);     
  /* GPIO_B_PEREN: PE3=0,PE2=0 */
  clrReg16Bits(GPIO_B_PEREN, 0x0CU);    
  /* INTC_IPR4: PWM_RELOAD2_IPL=0,PWM_CMP3_IPL=0,PWM_CAP3_IPL=0,PWM_RELOAD3_IPL=0,PWM_RERR_IPL=0,PWM_FAULT_IPL=2,TMRA_0_IPL=2,TMRA_1_IPL=2 */
  setReg16(INTC_IPR4, 0x2AU);           
  /* TMRA_ENBL: ENBL&=~7 */
  clrReg16Bits(TMRA_ENBL, 0x07U);       
  /* INTC_IPR5: PWM_CMP0_IPL=0,PWM_RELOAD0_IPL=2,PWM_CMP1_IPL=0,PWM_RELOAD1_IPL=0,PWM_CMP2_IPL=0 */
  clrSetReg16Bits(INTC_IPR5, 0x037FU, 0x80U); 
  /* GPIO_E_PEREN: PE5=1,PE4=1,PE3=1,PE2=1,PE1=1,PE0=1 */
  setReg16Bits(GPIO_E_PEREN, 0x3FU);    
  /* SIM_GPS3: E5=0,E4=0,??=0 */
  clrReg16Bits(SIM_GPS3, 0x52U);        
  /* GPIO_C_PEREN: PE6=1,PE4=1,PE3=1,PE2=1 */
  setReg16Bits(GPIO_C_PEREN, 0x5CU);    
  /* SIM_GPS0: C6=0,C4=0,C3=0,C2=0 */
  clrReg16Bits(SIM_GPS0, 0x31F0U);      
  /* GPIO_C_PUPEN: PU6=0,PU4=0,PU3=1 */
  clrSetReg16Bits(GPIO_C_PUPEN, 0x50U, 0x08U); 
  /* INTC_IPR3: TMRA_2_IPL=2,QSCI0_TDRE_IPL=2 */
  clrSetReg16Bits(INTC_IPR3, 0x4004U, 0x8008U); 
  /* GPIO_F_PEREN: PE8=1 */
  setReg16Bits(GPIO_F_PEREN, 0x0100U);  
  /* INTC_IPR2: QSCI0_RCV_IPL=2 */
  clrSetReg16Bits(INTC_IPR2, 0x4000U, 0x8000U); 
  /* Disable peripheral clock after initialization of their registers (if the clocks should not be enabled in init. code) */
  /* SIM_PCE0: TA3=0,TB0=0,TB1=0,TB2=0,TB3=0,ADC=0,GPIOA=0,GPIOC=0,GPIOD=0,GPIOE=0,GPIOF=0,??=0 */
  clrReg16Bits(SIM_PCE0, 0x1FDFU);     /* Disable prph.clocks in the SIM_PCE0 register after Common initialization */ 
  /* SIM_PCE1: ??=0,DAC=0,CMPA=0,CMPB=0,CMPC=0,SCI1=0,QSPI0=0,IIC0=0,IIC1=0,CRC=0,REFA=0,REFB=0,REFC=0 */
  clrReg16Bits(SIM_PCE1, 0xFBFCU);     /* Disable prph.clocks in the SIM_PCE1 register after Common initialization */ 
  /* SIM_PCE2: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,PWMCH3=0 */
  clrReg16Bits(SIM_PCE2, 0xFFF1U);     /* Disable prph.clocks in the SIM_PCE2 register after Common initialization */ 
  /* ### TimerInt "TI1" init code ... */
  TI1_Init();
  /* ### Init_eFlexPWM "eFlexPWM" init code ... */
  /* ### Call "eFlexPWM_Init();" init method in a user code, i.e. in the main code */

  /* ### Note:   To enable automatic calling of the "eFlexPWM" init code here,
                 the 'Call Init method' property must be set to 'yes'.
   */
  /* ### Timer capture encapsulation "Cap1" init code ... */
  Cap1_Init();
  /* ### Timer capture encapsulation "Cap2" init code ... */
  Cap2_Init();
  /* ### PWMMC "PWMC1" init code ... */
  PWMC1_Init();


  /* ### Timer capture encapsulation "Cap3" init code ... */
  Cap3_Init();
  /* ### Init_SCI "QSCI0" init code ... */
  QSCI0_Init();

  /* ### FreeMaster "FMSTR1" init code ... */
  FMSTR1_Init();
  /* ### TimerInt "TI2" init code ... */
  TI2_Init();
  /* Common peripheral initialization - ENABLE */
  /* TMRA_ENBL: ENBL|=7 */
  setReg16Bits(TMRA_ENBL, 0x07U);       
  setRegBitGroup(TMRA0_CTRL,CM,0x01);
  setRegBitGroup(TMRA1_CTRL,CM,0x01);
  __EI(0);                             /* Enable interrupts of the selected priority level */
}

/* END Cpu. */

